# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/fixtures/**/*'

# TO REMOVE!
Lint/UnreachableCode:
  Enabled: false
# END TO REMOVE!

Style/RescueModifier:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/IndentationWidth:
  Enabled: false
