#!/usr/bin/env ruby

require_relative "lib/info"

# Stage files so they are considered by the gemspec:
# http://stackoverflow.com/a/13190785/167983
%x[git add -A] 

spec = Gem::Specification::load("git-multirepo.gemspec")

puts "Building #{spec.name} #{spec.version}..."
%x[gem build git-multirepo.gemspec]

puts "Installing gem..."
%x[gem install git-multirepo-#{MultiRepo::VERSION}.gem]

puts "Done!"
