#!/usr/bin/env ruby

require "rubygems"
require "git-multirepo"

entries =  MultiRepo::ConfigFile.load_entries
uncommited = MultiRepo::Utils.check_for_uncommited_changes(entries)

if uncommited
  MultiRepo::Console.log_error("You must commit changes to your dependencies before you can commit the main repo")
  exit 1
end

MultiRepo::LockFile.update
MultiRepo::Console.log_info("Updated and staged lock file with current HEAD revisions for all dependencies")

exit 0 # Success!