require_relative "multirepo/commands/command"
require_relative "multirepo/commands/add"
require_relative "multirepo/commands/edit"
require_relative "multirepo/commands/fetch"
require_relative "multirepo/commands/init"
require_relative "multirepo/commands/install"
require_relative "multirepo/commands/open"